// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBuRequestBucket = "bu_request_buckets"

// BuRequestBucket mapped from table <bu_request_buckets>
type BuRequestBucket struct {
	ID                     int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID                 int32          `gorm:"column:user_id;not null" json:"user_id"`
	BusinessUnitLevel      string         `gorm:"column:business_unit_level;not null" json:"business_unit_level"`
	BusinessUnitLocationID int32          `gorm:"column:business_unit_location_id;not null" json:"business_unit_location_id"`
	BusinessUnitLocation   string         `gorm:"column:business_unit_location;not null" json:"business_unit_location"`
	Status                 string         `gorm:"column:status;not null" json:"status"`
	ReviewedBy             *string        `gorm:"column:reviewed_by" json:"reviewed_by"`
	ReviewedAt             *time.Time     `gorm:"column:reviewed_at" json:"reviewed_at"`
	CreatedBy              string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt              time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedBy              string         `gorm:"column:updated_by;not null" json:"updated_by"`
	UpdatedAt              time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedBy              *string        `gorm:"column:deleted_by" json:"deleted_by"`
	DeletedAt              gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	ActivityLogID          *string        `gorm:"column:activity_log_id" json:"activity_log_id"`
}

// TableName BuRequestBucket's table name
func (*BuRequestBucket) TableName() string {
	return TableNameBuRequestBucket
}
