// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoleResourceMapping = "role_resource_mappings"

// RoleResourceMapping mapped from table <role_resource_mappings>
type RoleResourceMapping struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID     int32          `gorm:"column:role_id;not null" json:"role_id"`
	ResourceID int32          `gorm:"column:resource_id;not null" json:"resource_id"`
	CreatedBy  string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedBy  string         `gorm:"column:updated_by;not null" json:"updated_by"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedBy  *string        `gorm:"column:deleted_by" json:"deleted_by"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RoleResourceMapping's table name
func (*RoleResourceMapping) TableName() string {
	return TableNameRoleResourceMapping
}
