// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTempRoleResourceMapping = "temp_role_resource_mappings"

// TempRoleResourceMapping mapped from table <temp_role_resource_mappings>
type TempRoleResourceMapping struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID     int32          `gorm:"column:role_id;not null" json:"role_id"`
	MenuID     int32          `gorm:"column:menu_id;not null" json:"menu_id"`
	SubmenuID  int32          `gorm:"column:submenu_id;not null" json:"submenu_id"`
	FunctionID int32          `gorm:"column:function_id;not null" json:"function_id"`
	CreatedBy  string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt  time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedBy  string         `gorm:"column:updated_by;not null" json:"updated_by"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedBy  *string        `gorm:"column:deleted_by" json:"deleted_by"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName TempRoleResourceMapping's table name
func (*TempRoleResourceMapping) TableName() string {
	return TableNameTempRoleResourceMapping
}
