// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTempUser = "temp_users"

// TempUser mapped from table <temp_users>
type TempUser struct {
	ID                           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID                       int32          `gorm:"column:user_id;not null" json:"user_id"`
	Username                     string         `gorm:"column:username;not null" json:"username"`
	Description                  string         `gorm:"column:description;not null" json:"description"`
	FullName                     string         `gorm:"column:full_name;not null" json:"full_name"`
	Email                        string         `gorm:"column:email;not null" json:"email"`
	PhoneNumber                  *string        `gorm:"column:phone_number" json:"phone_number"`
	BusinessUnitLevel            *string        `gorm:"column:business_unit_level" json:"business_unit_level"`
	BusinessUnitLocationID       *int32         `gorm:"column:business_unit_location_id" json:"business_unit_location_id"`
	BusinessUnitLocation         *string        `gorm:"column:business_unit_location" json:"business_unit_location"`
	BusinessUnitAssignmentStatus *string        `gorm:"column:business_unit_assignment_status" json:"business_unit_assignment_status"`
	SupplierID                   *int32         `gorm:"column:supplier_id" json:"supplier_id"`
	SupplierName                 *string        `gorm:"column:supplier_name" json:"supplier_name"`
	AssignedRoles                *string        `gorm:"column:assigned_roles" json:"assigned_roles"`
	CreatedBy                    string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt                    time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedBy                    string         `gorm:"column:updated_by;not null" json:"updated_by"`
	UpdatedAt                    time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedBy                    *string        `gorm:"column:deleted_by" json:"deleted_by"`
	DeletedAt                    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName TempUser's table name
func (*TempUser) TableName() string {
	return TableNameTempUser
}
