// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserRoleMapping = "user_role_mappings"

// UserRoleMapping mapped from table <user_role_mappings>
type UserRoleMapping struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    *int32         `gorm:"column:user_id" json:"user_id"`
	RoleID    *int32         `gorm:"column:role_id" json:"role_id"`
	CreatedBy string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedBy string         `gorm:"column:updated_by;not null" json:"updated_by"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedBy *string        `gorm:"column:deleted_by" json:"deleted_by"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserRoleMapping's table name
func (*UserRoleMapping) TableName() string {
	return TableNameUserRoleMapping
}
