// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"golang-auth-app/app/adapters/sql/gorm/model"
)

func newFunction(db *gorm.DB, opts ...gen.DOOption) function {
	_function := function{}

	_function.functionDo.UseDB(db, opts...)
	_function.functionDo.UseModel(&model.Function{})

	tableName := _function.functionDo.TableName()
	_function.ALL = field.NewAsterisk(tableName)
	_function.ID = field.NewInt32(tableName, "id")
	_function.SubmenuID = field.NewInt32(tableName, "submenu_id")
	_function.Name = field.NewString(tableName, "name")
	_function.PublicName = field.NewString(tableName, "public_name")
	_function.Description = field.NewString(tableName, "description")
	_function.CreatedBy = field.NewString(tableName, "created_by")
	_function.CreatedAt = field.NewTime(tableName, "created_at")
	_function.UpdatedBy = field.NewString(tableName, "updated_by")
	_function.UpdatedAt = field.NewTime(tableName, "updated_at")
	_function.DeletedBy = field.NewString(tableName, "deleted_by")
	_function.DeletedAt = field.NewField(tableName, "deleted_at")

	_function.fillFieldMap()

	return _function
}

type function struct {
	functionDo functionDo

	ALL         field.Asterisk
	ID          field.Int32
	SubmenuID   field.Int32
	Name        field.String
	PublicName  field.String
	Description field.String
	CreatedBy   field.String
	CreatedAt   field.Time
	UpdatedBy   field.String
	UpdatedAt   field.Time
	DeletedBy   field.String
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (f function) Table(newTableName string) *function {
	f.functionDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f function) As(alias string) *function {
	f.functionDo.DO = *(f.functionDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *function) updateTableName(table string) *function {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt32(table, "id")
	f.SubmenuID = field.NewInt32(table, "submenu_id")
	f.Name = field.NewString(table, "name")
	f.PublicName = field.NewString(table, "public_name")
	f.Description = field.NewString(table, "description")
	f.CreatedBy = field.NewString(table, "created_by")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedBy = field.NewString(table, "updated_by")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.DeletedBy = field.NewString(table, "deleted_by")
	f.DeletedAt = field.NewField(table, "deleted_at")

	f.fillFieldMap()

	return f
}

func (f *function) WithContext(ctx context.Context) IFunctionDo { return f.functionDo.WithContext(ctx) }

func (f function) TableName() string { return f.functionDo.TableName() }

func (f function) Alias() string { return f.functionDo.Alias() }

func (f function) Columns(cols ...field.Expr) gen.Columns { return f.functionDo.Columns(cols...) }

func (f *function) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *function) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 11)
	f.fieldMap["id"] = f.ID
	f.fieldMap["submenu_id"] = f.SubmenuID
	f.fieldMap["name"] = f.Name
	f.fieldMap["public_name"] = f.PublicName
	f.fieldMap["description"] = f.Description
	f.fieldMap["created_by"] = f.CreatedBy
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_by"] = f.UpdatedBy
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_by"] = f.DeletedBy
	f.fieldMap["deleted_at"] = f.DeletedAt
}

func (f function) clone(db *gorm.DB) function {
	f.functionDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f function) replaceDB(db *gorm.DB) function {
	f.functionDo.ReplaceDB(db)
	return f
}

type functionDo struct{ gen.DO }

type IFunctionDo interface {
	gen.SubQuery
	Debug() IFunctionDo
	WithContext(ctx context.Context) IFunctionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFunctionDo
	WriteDB() IFunctionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFunctionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFunctionDo
	Not(conds ...gen.Condition) IFunctionDo
	Or(conds ...gen.Condition) IFunctionDo
	Select(conds ...field.Expr) IFunctionDo
	Where(conds ...gen.Condition) IFunctionDo
	Order(conds ...field.Expr) IFunctionDo
	Distinct(cols ...field.Expr) IFunctionDo
	Omit(cols ...field.Expr) IFunctionDo
	Join(table schema.Tabler, on ...field.Expr) IFunctionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFunctionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFunctionDo
	Group(cols ...field.Expr) IFunctionDo
	Having(conds ...gen.Condition) IFunctionDo
	Limit(limit int) IFunctionDo
	Offset(offset int) IFunctionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFunctionDo
	Unscoped() IFunctionDo
	Create(values ...*model.Function) error
	CreateInBatches(values []*model.Function, batchSize int) error
	Save(values ...*model.Function) error
	First() (*model.Function, error)
	Take() (*model.Function, error)
	Last() (*model.Function, error)
	Find() ([]*model.Function, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Function, err error)
	FindInBatches(result *[]*model.Function, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Function) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFunctionDo
	Assign(attrs ...field.AssignExpr) IFunctionDo
	Joins(fields ...field.RelationField) IFunctionDo
	Preload(fields ...field.RelationField) IFunctionDo
	FirstOrInit() (*model.Function, error)
	FirstOrCreate() (*model.Function, error)
	FindByPage(offset int, limit int) (result []*model.Function, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFunctionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f functionDo) Debug() IFunctionDo {
	return f.withDO(f.DO.Debug())
}

func (f functionDo) WithContext(ctx context.Context) IFunctionDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f functionDo) ReadDB() IFunctionDo {
	return f.Clauses(dbresolver.Read)
}

func (f functionDo) WriteDB() IFunctionDo {
	return f.Clauses(dbresolver.Write)
}

func (f functionDo) Session(config *gorm.Session) IFunctionDo {
	return f.withDO(f.DO.Session(config))
}

func (f functionDo) Clauses(conds ...clause.Expression) IFunctionDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f functionDo) Returning(value interface{}, columns ...string) IFunctionDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f functionDo) Not(conds ...gen.Condition) IFunctionDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f functionDo) Or(conds ...gen.Condition) IFunctionDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f functionDo) Select(conds ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f functionDo) Where(conds ...gen.Condition) IFunctionDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f functionDo) Order(conds ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f functionDo) Distinct(cols ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f functionDo) Omit(cols ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f functionDo) Join(table schema.Tabler, on ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f functionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f functionDo) RightJoin(table schema.Tabler, on ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f functionDo) Group(cols ...field.Expr) IFunctionDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f functionDo) Having(conds ...gen.Condition) IFunctionDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f functionDo) Limit(limit int) IFunctionDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f functionDo) Offset(offset int) IFunctionDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f functionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFunctionDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f functionDo) Unscoped() IFunctionDo {
	return f.withDO(f.DO.Unscoped())
}

func (f functionDo) Create(values ...*model.Function) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f functionDo) CreateInBatches(values []*model.Function, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f functionDo) Save(values ...*model.Function) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f functionDo) First() (*model.Function, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Function), nil
	}
}

func (f functionDo) Take() (*model.Function, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Function), nil
	}
}

func (f functionDo) Last() (*model.Function, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Function), nil
	}
}

func (f functionDo) Find() ([]*model.Function, error) {
	result, err := f.DO.Find()
	return result.([]*model.Function), err
}

func (f functionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Function, err error) {
	buf := make([]*model.Function, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f functionDo) FindInBatches(result *[]*model.Function, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f functionDo) Attrs(attrs ...field.AssignExpr) IFunctionDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f functionDo) Assign(attrs ...field.AssignExpr) IFunctionDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f functionDo) Joins(fields ...field.RelationField) IFunctionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f functionDo) Preload(fields ...field.RelationField) IFunctionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f functionDo) FirstOrInit() (*model.Function, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Function), nil
	}
}

func (f functionDo) FirstOrCreate() (*model.Function, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Function), nil
	}
}

func (f functionDo) FindByPage(offset int, limit int) (result []*model.Function, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f functionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f functionDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f functionDo) Delete(models ...*model.Function) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *functionDo) withDO(do gen.Dao) *functionDo {
	f.DO = *do.(*gen.DO)
	return f
}
