// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameActivityLog = "activity_logs"

// ActivityLog mapped from table <activity_logs>
type ActivityLog struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ActivityLogID string         `gorm:"column:activity_log_id;not null" json:"activity_log_id"`
	Message       string         `gorm:"column:message;not null" json:"message"`
	Status        string         `gorm:"column:status;not null" json:"status"`
	CreatedBy     string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt     *time.Time     `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedBy     *string        `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedBy     *string        `gorm:"column:deleted_by" json:"deleted_by"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName ActivityLog's table name
func (*ActivityLog) TableName() string {
	return TableNameActivityLog
}
