// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username          string         `gorm:"column:username;not null" json:"username"`
	Description       string         `gorm:"column:description;not null" json:"description"`
	FullName          string         `gorm:"column:full_name;not null" json:"full_name"`
	Email             string         `gorm:"column:email;not null" json:"email"`
	PhoneNumber       *string        `gorm:"column:phone_number" json:"phone_number"`
	Password          string         `gorm:"column:password;not null" json:"password"`
	IsDefaultPassword bool           `gorm:"column:is_default_password;not null;default:true" json:"is_default_password"`
	Type              string         `gorm:"column:type;not null" json:"type"`
	Status            string         `gorm:"column:status;not null" json:"status"`
	StartDate         *time.Time     `gorm:"column:start_date" json:"start_date"`
	EndDate           *time.Time     `gorm:"column:end_date" json:"end_date"`
	AssignedRoles     *string        `gorm:"column:assigned_roles" json:"assigned_roles"`
	CreatedBy         string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedBy         string         `gorm:"column:updated_by;not null" json:"updated_by"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedBy         *string        `gorm:"column:deleted_by" json:"deleted_by"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	ActivityLogID     *string        `gorm:"column:activity_log_id" json:"activity_log_id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
